---
title: "Introduction to ggplot with regression"
author: "Antonio Rodriguez Andres"
date: "28 de enero de 2019"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries}
library(tidyverse)
library(gapminder)
library(ggplot2)
library(ggthemes)
```

```{r average life expectancy}
gapminder %>% 
  group_by(country) %>% 
  summarize(av.le = mean(lifeExp)) %>% 
  arrange(desc(av.le))
```

```{r average per capita GDP}
gapminder %>% 
  group_by(country) %>% 
summarize(av.income = mean(gdpPercap))
```

```{r boxplot life expectancy}
gapminder %>% 
  ggplot(aes(x = factor(0), y = lifeExp)) + 
  geom_boxplot(aes(color = continent)) +
  facet_wrap(~continent)
```




```{r scatter plot GDP vs. life Expectancy}
gapminder %>% ggplot(aes(x = log(gdpPercap), y = lifeExp, col = continent)) +
  geom_point()

```


```{r similar to the Economist}
gapminder %>% ggplot(aes(x = log(gdpPercap), y = lifeExp)) +
  geom_point() + geom_smooth(lwd = 1, se = TRUE, method = 'lm') + theme_economist() + ggtitle('GDP per capita vs. Life Expectancy')

```

